### ISSUE TITLE
Website should be update.

### ISSUE THREAD

**Issue by katabame** [karno/StarryEyes#181]
Hello karno.
This is a not important issue, but I just wanted let you know.

In the Krile StarryEyes official website ([krile.starwing.net](http://krile.starwing.net/)), download link is still linked to version 3.0.0
Krile has auto update system and user will got latest version, but linking to latest version is good thing.

Thanks for your hard work. and I'm cheering up for the next generation of Krile.

**Comment by karno** [comment]
Hello, katabame.
Thank you for your feedback and I have updated the official website and have released 3.1.0 via web.

Usually, updates are published on the auto-update channel at first, due to checking compatibility, stability, and so on...
Therefore, starting distribution on the web may delayed with half a day or a few days compared to auto-update channel.

I apologize for inconvenience with slower update, and this situation might continue by beginning of next spring.
